# Generated by Django 5.2.15 on 2026-07-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('PRODUCT', 'Product'), ('CATEGORY', 'Category')], default='', max_length=20),
        ),
    ]
