# Generated by Django 5.2.15 on 2026-07-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_productimage_productvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_price',
        ),
    ]
