# Generated by Django 5.2.15 on 2026-07-05 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sku',
            new_name='product_sku',
        ),
    ]
